config/routes.rb
Community::Engine.routes.draw do
  resources :forums
  root to: "forums#index"
end

app/models/community/application_record.rb
module Community
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/community/forum.rb
module Community
  class Forum < ApplicationRecord
  end
end

app/controllers/community/application_controller.rb
module Community
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/community/forums_controller.rb
require_dependency "community/application_controller"

module Community
  class ForumsController < ApplicationController
    before_action :set_forum, only: [:show, :edit, :update, :destroy]

    # GET /forums
    def index
      @forums = Forum.all
    end

    # GET /forums/1
    def show
    end

    # GET /forums/new
    def new
      @forum = Forum.new
    end

    # GET /forums/1/edit
    def edit
    end

    # POST /forums
    def create
      @forum = Forum.new(forum_params)

      if @forum.save
        redirect_to @forum, notice: 'Forum was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /forums/1
    def update
      if @forum.update(forum_params)
        redirect_to @forum, notice: 'Forum was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /forums/1
    def destroy
      @forum.destroy
      redirect_to forums_url, notice: 'Forum was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_forum
        @forum = Forum.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def forum_params
        params.require(:forum).permit(:name, :description)
      end
  end
end

app/helpers/community/application_helper.rb
module Community
  module ApplicationHelper
  end
end

app/helpers/community/forums_helper.rb
module Community
  module ForumsHelper
  end
end

app/views/community/forums/_form.html.erb
<%= form_with(model: forum, local: true) do |form| %>
  <% if forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :forum_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :forum_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/community/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/community/forums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forums.each do |forum| %>
      <tr>
        <td><%= forum.name %></td>
        <td><%= forum.description %></td>
        <td><%= link_to 'Show', forum %></td>
        <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
        <td><%= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum', new_forum_path %>

app/views/community/forums/new.html.erb
<h1>New Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Back', forums_path %>

app/views/community/forums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @forum.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @forum.description %>
</p>

<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>

app/views/layouts/community/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community</title>
  <%= stylesheet_link_tag    "community/application", media: "all" %>
  <%= javascript_include_tag "community/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>